# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Thecodelessctl < Formula
  desc ""
  homepage ""
  version "0.0.5"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/jasonblanchard/thecodelessctl/releases/download/v0.0.5/thecodelessctl_0.0.5_Darwin_x86_64.tar.gz"
    sha256 "6397adf094b39cbf9547dbbf288a505a96ae944ce85d74e1699ab69ec02ff8db"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/jasonblanchard/thecodelessctl/releases/download/v0.0.5/thecodelessctl_0.0.5_Darwin_arm64.tar.gz"
    sha256 "2a53227ef43707e299ed9f84962ccddf575108f9aec9684c79b1e5f6004a5ea3"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/jasonblanchard/thecodelessctl/releases/download/v0.0.5/thecodelessctl_0.0.5_Linux_x86_64.tar.gz"
    sha256 "c2ce47c187c0b5be873d7db917d0f3ab8325891eb1cc64ef1b405888f6800cb7"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/jasonblanchard/thecodelessctl/releases/download/v0.0.5/thecodelessctl_0.0.5_Linux_arm64.tar.gz"
    sha256 "21f2cb2075879f717b9264e18f565f2a2b7c04654abf87e159e7fdde3892d4ec"
  end

  def install
    bin.install "thecodelessctl"
  end
end
